### ISSUE TITLE
Not compatible with D-pad

### ISSUE THREAD

**Issue by zipswich** [hedzr/android-file-chooser#47] opened 2019-02-26 21:34 UTC
Unable to use D-pad to click the OK or Cancel button.  The focus will not stay on them.  Very strange.
This has been confirmed on both physical devices and emulators.

**Comment by hedzr** [comment] 2019-02-26 23:52
you're so kind. i'll review it asap.

**Comment by Guiorgy** [comment] 2019-03-03 10:43
@zipswich, if the problem is still there, would you mind trying my implementation of D-pad? It's a bit different. (you do need to enable it though __.enableDpad(true)__)

**Comment by hedzr** [comment] 2019-03-03 12:26
I had already fixed at commit 84b825d but wrong issue number. :(

**Comment by Guiorgy** [comment] 2019-03-03 12:58
oh

**Comment by zipswich** [comment] 2019-03-04 14:10
I am sorry but I missed the fix.  Thanks a lot for the effort.
Anyway,  I have just tried it.  There seems to be no more "OK" button.  It has only Cancel button:
![image](https://user-images.githubusercontent.com/6095671/53738539-6f32ed80-3e5d-11e9-8a11-6518499e7e46.png)

**Comment by Guiorgy** [comment] 2019-03-04 15:15
@zipswich, what setting/filters are you using? Depending on that, the button will/will not be visible.

**Comment by zipswich** [comment] 2019-03-04 16:34
@Guiorgy Here is my code:
```
                        new ChooserDialog(SettingsActivity.this)
                                .titleFollowsDir(true)
                                .withResources(R.string.choose_folder, R.string.ok, R.string.cancel)
                                .withStartFile(dirDefault.getAbsolutePath())
                                // to handle the result(s)
                                .withChosenListener((path, pathFile) -> {
```

**Comment by Guiorgy** [comment] 2019-03-05 07:51
@zipswich, sorry for the late relpy.
```java
if (_dirOnly || _enableMultiple) {
    // choosing folder, or multiple files picker
    builder.setPositiveButton(_okRes, (dialog, which) -> {
        if (_result != null) {
             _result.onChoosePath(_currentDir.getAbsolutePath(), _currentDir);
        }
    });
}
```

In other words, your code is for choosing a single **file**, which you can select by clicking on it in the list. The button apears if you either want to choose a **directory/folder** or choose several **files**.

for example, _selecting directory_:
```java
.withFilter(/*choose directory*/ true, /*allow hidden files/folders*/ false);
```

**Comment by zipswich** [comment] 2019-03-05 16:18
@Guiorgy Thank you for the elucidation.  
Yes, I can confirm that that both OK and Cancel buttons are displayed for selecting a directory, and either can be selected with D-pad. 
The remaining problem for D-pad operation is the  center (enter) button does not work for OK or Cancel.  In other words, neither button works with D-pad.

**Comment by hedzr** [comment] 2019-03-06 00:01
I hope it works now

**Comment by zipswich** [comment] 2019-03-06 02:46
Thank you.  Should I still use the following?
`implementation 'com.obsez.android.lib.filechooser:filechooser:1.1.16'`
I have just built an app, D-pad still does not work.

**Comment by hedzr** [comment] 2019-03-06 03:07
Temporarily, you might need to switch to jitpack.io for the patch d7b831b. Try this one:
https://jitpack.io/#hedzr/android-file-chooser/d7b831bf0a

```gradle
	dependencies {
	        implementation 'com.github.hedzr:android-file-chooser:d7b831bf0a'
	}
```

**Comment by zipswich** [comment] 2019-03-06 03:11
Thank you. 
I got the following error in Android Studio:

> ERROR: Failed to resolve: com.github.hedzr:android-file-chooser:d7b831bf0a

**Comment by hedzr** [comment] 2019-03-06 03:15
Try again and you'll find it. jitpack.io need a while for building at first request.

You could check [that page](https://jitpack.io/#hedzr/android-file-chooser/d7b831bf0a). It had been built successfully. see also: https://jitpack.io/com/github/hedzr/android-file-chooser/master-v1.1.10-gd7b831b-149/build.log

**Comment by zipswich** [comment] 2019-03-06 03:26
Not sure why I still get the following error:
```
Could not find com.github.hedzr:android-file-chooser:d7b831bf0a.
  Searched in the following locations:
    - https://dl.google.com/dl/android/maven2/com/github/hedzr/android-file-chooser/d7b831bf0a/android-file-chooser-d7b831bf0a.pom
    - https://dl.google.com/dl/android/maven2/com/github/hedzr/android-file-chooser/d7b831bf0a/android-file-chooser-d7b831bf0a.jar
    - https://jcenter.bintray.com/com/github/hedzr/android-file-chooser/d7b831bf0a/android-file-chooser-d7b831bf0a.pom
    - https://jcenter.bintray.com/com/github/hedzr/android-file-chooser/d7b831bf0a/android-file-chooser-d7b831bf0a.jar
    - https://repo.maven.apache.org/maven2/com/github/hedzr/android-file-chooser/d7b831bf0a/android-file-chooser-d7b831bf0a.pom
    - https://repo.maven.apache.org/maven2/com/github/hedzr/android-file-chooser/d7b831bf0a/android-file-chooser-d7b831bf0a.jar
```

**Comment by hedzr** [comment] 2019-03-06 03:38
did you put jitpack ref to your top-level build.gradle, like the README?

it looks like:
```gradle
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
take a look about README or https://jitpack.io/#hedzr/android-file-chooser/d7b831bf0a.

**Comment by zipswich** [comment] 2019-03-06 03:41
Yes, I copied the code from the page:
![image](https://user-images.githubusercontent.com/6095671/53854532-d3f26300-3f97-11e9-8e5f-e0f2e5ac4d80.png)

**Comment by hedzr** [comment] 2019-03-06 03:45
How about moving these lines up to your TOP-LEVEL `build.gradle`?

**Comment by zipswich** [comment] 2019-03-06 04:03
Now, I am getting:
> Task :app:transformDexArchiveWithExternalLibsDexMergerForOfficialDebug FAILED
`AGPBI: {"kind":"error","text":"Program type already present: com.obsez.android.lib.filechooser.ChooserDialog$Result","sources":[{}],"tool":"D8"}`

Perhaps I should just wait for the fix to reach the normal channel.

**Comment by hedzr** [comment] 2019-03-06 04:13
:).
I could be not publish a release in these days and it seems be fast.

About the error, it looks like you have multiple implements of **this library** with multiple version.
Anyway, you could rebuild since the duplicated symbols; and try add java 8 declares at your app/build.gradle.

**Comment by zipswich** [comment] 2019-03-06 04:33
The problem is probably related to AFC used in a library.  The library can be built, but the app including the library cannot be built.  I will try a few things to get back here to report the outcome.

**Comment by zipswich** [comment] 2019-03-06 13:14
I have finally got it to work.  I need to apologize for forgetting that the app's gradle file must have the same script as the library's grade file to use AFC even though the app does not have any code using AFC. 

The Cancel button works exactly as expected - it can be focused with D-pad arrow keys and selected with the center key.  However, the OK button is selected automatically as soon as it gets the focus without using the center button.   I think the OK button should behave exactly the same way as the OK button.

**Comment by hedzr** [comment] 2019-03-11 23:33
Sorry for late to reply.
I have not any dpad simulate device or emulator currently, so this case is hard to reproduced.
But here is a slight patch because it looks like the basic reason.

**Comment by Guiorgy** [comment] 2019-04-08 11:35
![dpad_demo](https://user-images.githubusercontent.com/27736965/55720938-1b469600-5a13-11e9-8953-70cf86f4af11.gif)

if you are still having problems, you can try the experimental branch

**Comment by Guiorgy** [comment] 2019-05-08 12:35
are you still having issues with the new release? If not, then please consider closing this issue

**Comment by zipswich** [comment] 2021-10-28 19:25
@Guiorgy Very sorry but I have just realized that I somehow missed the Github notification. It works fine now.

**Closed as completed** 2021-10-28 20:31 UTC
Labels: enhancement
